// <auto-generated />
using System;
using Leadzum.Framework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Leadzum.Framework.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Leadzum.Framework.Data.Entities.EventLog", b =>
                {
                    b.Property<long>("EventLogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LogCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("LogDetail")
                        .IsRequired();

                    b.Property<string>("LogMachineName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<bool?>("LogNotificationPending");

                    b.Property<int>("LogTypeId");

                    b.Property<int?>("LogUserId");

                    b.Property<string>("LogUserName")
                        .HasMaxLength(256);

                    b.HasKey("EventLogId");

                    b.HasIndex("LogTypeId");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("Leadzum.Framework.Data.Entities.EventLogType", b =>
                {
                    b.Property<int>("LogTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(256);

                    b.Property<bool?>("EmailNotificationIsActive");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("KeepMostRecent");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("LogCategory");

                    b.Property<bool>("LoggingIsActive");

                    b.Property<string>("MailToAddress")
                        .HasMaxLength(50);

                    b.HasKey("LogTypeId");

                    b.ToTable("EventLogTypes");

                    b.HasData(
                        new
                        {
                            LogTypeId = 1,
                            FriendlyName = "User Login Success",
                            Key = "LOGIN_SUCCESS",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 2,
                            FriendlyName = "User Login Failure",
                            Key = "LOGIN_FAILURE",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 3,
                            FriendlyName = "User Logout",
                            Key = "LOGOUT",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 4,
                            FriendlyName = "System Configuration Updated",
                            Key = "SYSTEM_CONFIG_UPDATED",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 5,
                            FriendlyName = "Data Synchronized",
                            Key = "DATA_SYNCED",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 6,
                            FriendlyName = "New User Created",
                            Key = "USER_CREATED",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 7,
                            FriendlyName = "New User Registered",
                            Key = "USER_REGISTERED",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 8,
                            FriendlyName = "User Updated",
                            Key = "USER_UPDATED",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 9,
                            FriendlyName = "User Deleted",
                            Key = "USER_DELETED",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 10,
                            FriendlyName = "User Restored",
                            Key = "USER_RESTORED",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 11,
                            FriendlyName = "User Removed",
                            Key = "USER_REMOVED",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 12,
                            FriendlyName = "User Password Changed",
                            Key = "USER_PSW_CHANGED",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 13,
                            FriendlyName = "New Role Created",
                            Key = "ROLE_CREATED",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 14,
                            FriendlyName = "Role Updated",
                            Key = "ROLE_REGISTERED",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 15,
                            FriendlyName = "Role Deleted",
                            Key = "ROLE_DELETED",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 16,
                            FriendlyName = "New Module Created",
                            Key = "MODULE_CREATED",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 17,
                            FriendlyName = "Module Updated",
                            Key = "MODULE_REGISTERED",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 18,
                            FriendlyName = "Module Deleted",
                            Key = "MODULE_DELETED",
                            LogCategory = 1,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 1000,
                            FriendlyName = "Task Scheduler Started",
                            Key = "TASK_SCHEDULER_START",
                            LogCategory = 2,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 1001,
                            FriendlyName = "Task Scheduler Stopped",
                            Key = "TASK_SCHEDULER_STOP",
                            LogCategory = 2,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 2000,
                            FriendlyName = "General Exception",
                            Key = "GENERAL_EXCEPTION",
                            LogCategory = 3,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 2001,
                            FriendlyName = "Web Service Exception",
                            Key = "WEB_SERVICE_EXCEPTION",
                            LogCategory = 3,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 2002,
                            FriendlyName = "Task Scheduler Exception",
                            Key = "TASK_SCHEDULER_EXCEPTION",
                            LogCategory = 3,
                            LoggingIsActive = true
                        },
                        new
                        {
                            LogTypeId = 2003,
                            FriendlyName = "Database Exception",
                            Key = "DB_EXCEPTION",
                            LogCategory = 3,
                            LoggingIsActive = true
                        });
                });

            modelBuilder.Entity("Leadzum.Framework.Data.Entities.List", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreatedByUserId");

                    b.Property<DateTime>("CreatedOnDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int?>("LastModifiedByUserId");

                    b.Property<DateTime>("LastModifiedOnDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("ListName")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("ParentId");

                    b.Property<int>("SortOrder");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Value")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("EntryId");

                    b.HasIndex("ParentId");

                    b.ToTable("Lists");

                    b.HasData(
                        new
                        {
                            EntryId = 1,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 193, DateTimeKind.Local).AddTicks(4360),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 193, DateTimeKind.Local).AddTicks(5225),
                            ListName = "DateFormat",
                            SortOrder = 0,
                            Text = "yyyy-MM-dd",
                            Value = "1"
                        },
                        new
                        {
                            EntryId = 2,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(499),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(507),
                            ListName = "DateFormat",
                            SortOrder = 1,
                            Text = "M/d/yyyy",
                            Value = "2"
                        },
                        new
                        {
                            EntryId = 3,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(815),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(815),
                            ListName = "DateFormat",
                            SortOrder = 2,
                            Text = "MM/dd/yyyy",
                            Value = "3"
                        },
                        new
                        {
                            EntryId = 4,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(906),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(906),
                            ListName = "DateFormat",
                            SortOrder = 3,
                            Text = "MMM d, yyyy",
                            Value = "4"
                        },
                        new
                        {
                            EntryId = 5,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(985),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(985),
                            ListName = "DateFormat",
                            SortOrder = 4,
                            Text = "MMM dd, yyyy",
                            Value = "5"
                        },
                        new
                        {
                            EntryId = 6,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1064),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1064),
                            ListName = "DateFormat",
                            SortOrder = 5,
                            Text = "d/M/yyyy",
                            Value = "6"
                        },
                        new
                        {
                            EntryId = 7,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1143),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1143),
                            ListName = "DateFormat",
                            SortOrder = 6,
                            Text = "dd/MM/yyyy",
                            Value = "7"
                        },
                        new
                        {
                            EntryId = 8,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1214),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1214),
                            ListName = "DateFormat",
                            SortOrder = 7,
                            Text = "d MMM, yyyy",
                            Value = "8"
                        },
                        new
                        {
                            EntryId = 9,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1285),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1285),
                            ListName = "DateFormat",
                            SortOrder = 8,
                            Text = "dd MMM, yyyy",
                            Value = "9"
                        },
                        new
                        {
                            EntryId = 10,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1364),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1368),
                            ListName = "DateFormat",
                            SortOrder = 9,
                            Text = "dd-MMM-yyyy",
                            Value = "10"
                        },
                        new
                        {
                            EntryId = 11,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1664),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1664),
                            ListName = "LongTimeFormat",
                            SortOrder = 0,
                            Text = "h:mm:ss tt",
                            Value = "1"
                        },
                        new
                        {
                            EntryId = 12,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1842),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1842),
                            ListName = "LongTimeFormat",
                            SortOrder = 1,
                            Text = "hh:mm:ss tt",
                            Value = "2"
                        },
                        new
                        {
                            EntryId = 13,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1917),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1917),
                            ListName = "LongTimeFormat",
                            SortOrder = 2,
                            Text = "H:mm:ss",
                            Value = "3"
                        },
                        new
                        {
                            EntryId = 14,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1988),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(1988),
                            ListName = "LongTimeFormat",
                            SortOrder = 3,
                            Text = "HH:mm:ss",
                            Value = "4"
                        },
                        new
                        {
                            EntryId = 15,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2178),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2182),
                            ListName = "ShortTimeFormat",
                            SortOrder = 0,
                            Text = "h:mm tt",
                            Value = "1"
                        },
                        new
                        {
                            EntryId = 16,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2308),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2308),
                            ListName = "ShortTimeFormat",
                            SortOrder = 1,
                            Text = "hh:mm tt",
                            Value = "2"
                        },
                        new
                        {
                            EntryId = 17,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2383),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2383),
                            ListName = "ShortTimeFormat",
                            SortOrder = 2,
                            Text = "H:mm",
                            Value = "3"
                        },
                        new
                        {
                            EntryId = 18,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2533),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2533),
                            ListName = "ShortTimeFormat",
                            SortOrder = 3,
                            Text = "HH:mm",
                            Value = "4"
                        },
                        new
                        {
                            EntryId = 19,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2715),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2715),
                            ListName = "DataType",
                            SortOrder = 0,
                            Text = "Undefined",
                            Value = "0"
                        },
                        new
                        {
                            EntryId = 20,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2766),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2766),
                            ListName = "DataType",
                            SortOrder = 1,
                            Text = "Integer",
                            Value = "1"
                        },
                        new
                        {
                            EntryId = 21,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2774),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2778),
                            ListName = "DataType",
                            SortOrder = 2,
                            Text = "Text",
                            Value = "2"
                        },
                        new
                        {
                            EntryId = 22,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2782),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2786),
                            ListName = "DataType",
                            SortOrder = 3,
                            Text = "Boolean",
                            Value = "3"
                        },
                        new
                        {
                            EntryId = 23,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2790),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2790),
                            ListName = "DataType",
                            SortOrder = 4,
                            Text = "DateTime",
                            Value = "4"
                        },
                        new
                        {
                            EntryId = 24,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2798),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2798),
                            ListName = "DataType",
                            SortOrder = 5,
                            Text = "Image",
                            Value = "5"
                        },
                        new
                        {
                            EntryId = 25,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2873),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2873),
                            ListName = "LogCategory",
                            SortOrder = 0,
                            Text = "Admin Log",
                            Value = "1"
                        },
                        new
                        {
                            EntryId = 26,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2991),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(2991),
                            ListName = "LogCategory",
                            SortOrder = 1,
                            Text = "Maintenance Log",
                            Value = "2"
                        },
                        new
                        {
                            EntryId = 27,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(3067),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(3067),
                            ListName = "LogCategory",
                            SortOrder = 2,
                            Text = "Exception Log",
                            Value = "3"
                        },
                        new
                        {
                            EntryId = 28,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(3418),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(3418),
                            ListName = "LogCategory",
                            SortOrder = 0,
                            Text = "WebServiceUser",
                            Value = "1"
                        },
                        new
                        {
                            EntryId = 29,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(3517),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(3517),
                            ListName = "LogCategory",
                            SortOrder = 1,
                            Text = "SystemAdmin",
                            Value = "2"
                        },
                        new
                        {
                            EntryId = 30,
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(3568),
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 194, DateTimeKind.Local).AddTicks(3568),
                            ListName = "LogCategory",
                            SortOrder = 2,
                            Text = "SystemUser",
                            Value = "3"
                        });
                });

            modelBuilder.Entity("Leadzum.Framework.Data.Entities.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("CreatedByUserId");

                    b.Property<DateTime>("CreatedOnDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description")
                        .HasMaxLength(256);

                    b.Property<string>("IconFile")
                        .HasMaxLength(100);

                    b.Property<bool>("IsClickable");

                    b.Property<int?>("LastModifiedByUserId");

                    b.Property<DateTime>("LastModifiedOnDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("ParentId");

                    b.Property<int>("Type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<int>("ViewOrder");

                    b.HasKey("ModuleId");

                    b.HasIndex("ParentId");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            ModuleId = 1,
                            Area = "Admin",
                            Code = "DASHBOARD",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 205, DateTimeKind.Local).AddTicks(5683),
                            Description = "Dashboard",
                            IconFile = "fa fa-tachometer",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 205, DateTimeKind.Local).AddTicks(6457),
                            Name = "Dashboard",
                            Type = 1,
                            Url = "Home/Index",
                            ViewOrder = 1
                        },
                        new
                        {
                            ModuleId = 2,
                            Area = "Admin",
                            Code = "ADMIN_USER_AND_PERMISSIOIN",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4074),
                            Description = "User, role and permission management",
                            IconFile = "fa fa-users",
                            IsClickable = false,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4082),
                            Name = "User & Permission",
                            Type = 1,
                            Url = "",
                            ViewOrder = 2
                        },
                        new
                        {
                            ModuleId = 3,
                            Area = "Admin",
                            Code = "ADMIN_SYSTEM",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4137),
                            Description = "System configuration",
                            IconFile = "fa fa-cogs",
                            IsClickable = false,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4137),
                            Name = "System",
                            Type = 1,
                            Url = "",
                            ViewOrder = 3
                        },
                        new
                        {
                            ModuleId = 4,
                            Area = "Admin",
                            Code = "ADMIN_USER_MANAGEMENT",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4338),
                            Description = "User management",
                            IconFile = "fa fa-tachometer",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4338),
                            Name = "Users",
                            ParentId = 2,
                            Type = 1,
                            Url = "Admin/User/Index",
                            ViewOrder = 1
                        },
                        new
                        {
                            ModuleId = 5,
                            Area = "Admin",
                            Code = "ADMIN_ROLE_MANAGEMENT",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4342),
                            Description = "Role management",
                            IconFile = "fa fa-users",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4346),
                            Name = "Roles",
                            ParentId = 2,
                            Type = 1,
                            Url = "Admin/Role/Index",
                            ViewOrder = 2
                        },
                        new
                        {
                            ModuleId = 6,
                            Area = "Admin",
                            Code = "ADMIN_PERMISSION_MANAGEMENT",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4346),
                            Description = "Permission management",
                            IconFile = "fa fa-cogs",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4346),
                            Name = "Permissions",
                            ParentId = 2,
                            Type = 1,
                            Url = "Admin/Permission/Index",
                            ViewOrder = 3
                        },
                        new
                        {
                            ModuleId = 7,
                            Area = "Admin",
                            Code = "ADMIN_SYSTEM_CONFIG",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4354),
                            Description = "System configuration",
                            IconFile = "fa fa-tachometer",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4358),
                            Name = "Configuration",
                            ParentId = 3,
                            Type = 1,
                            Url = "Admin/System/Index",
                            ViewOrder = 1
                        },
                        new
                        {
                            ModuleId = 8,
                            Area = "Admin",
                            Code = "ADMIN_SYSTEM_MODULE",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4358),
                            Description = "System module management",
                            IconFile = "fa fa-users",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4358),
                            Name = "Modules",
                            ParentId = 3,
                            Type = 1,
                            Url = "Admin/Moudle/Index",
                            ViewOrder = 2
                        },
                        new
                        {
                            ModuleId = 9,
                            Area = "Admin",
                            Code = "ADMIN_SYSTEM_AUDIT",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4362),
                            Description = "System audit logs",
                            IconFile = "fa fa-cogs",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4362),
                            Name = "Audit Logs",
                            ParentId = 3,
                            Type = 1,
                            Url = "Admin/Audit/Index",
                            ViewOrder = 3
                        },
                        new
                        {
                            ModuleId = 10,
                            Area = "Admin",
                            Code = "ADMIN_SYSTEM_GENERAL",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4366),
                            Description = "System general settings",
                            IconFile = "fa fa-tachometer",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4370),
                            Name = "General",
                            ParentId = 7,
                            Type = 1,
                            Url = "Admin/System/General",
                            ViewOrder = 1
                        },
                        new
                        {
                            ModuleId = 11,
                            Area = "Admin",
                            Code = "ADMIN_SYSTEM_ADVANCED",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4370),
                            Description = "System advanced settings",
                            IconFile = "fa fa-users",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4370),
                            Name = "Advanced",
                            ParentId = 7,
                            Type = 1,
                            Url = "Admin/System/Advanced",
                            ViewOrder = 2
                        },
                        new
                        {
                            ModuleId = 12,
                            Area = "Admin",
                            Code = "ACTION_SYSTEM_GENERAL_EDIT",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4374),
                            Description = "Edit system general settings",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4374),
                            Name = "Edit",
                            ParentId = 10,
                            Type = 3,
                            Url = "Admin/System/GeneralEdit",
                            ViewOrder = 1
                        },
                        new
                        {
                            ModuleId = 13,
                            Area = "Admin",
                            Code = "ACTION_SYSTEM_ADVANCED_EDIT",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4378),
                            Description = "Edit system advanced settings",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4378),
                            Name = "Edit",
                            ParentId = 11,
                            Type = 3,
                            Url = "Admin/System/AdvancedEdit",
                            ViewOrder = 1
                        },
                        new
                        {
                            ModuleId = 14,
                            Area = "Admin",
                            Code = "ACTION_USER_ADD",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4382),
                            Description = "Add User",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4382),
                            Name = "Add User",
                            ParentId = 4,
                            Type = 3,
                            Url = "Admin/User/Add",
                            ViewOrder = 1
                        },
                        new
                        {
                            ModuleId = 15,
                            Area = "Admin",
                            Code = "ACTION_USER_EDIT",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4386),
                            Description = "Edit User",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4386),
                            Name = "Edit User",
                            ParentId = 4,
                            Type = 3,
                            Url = "Admin/User/Edit",
                            ViewOrder = 2
                        },
                        new
                        {
                            ModuleId = 16,
                            Area = "Admin",
                            Code = "ACTION_USER_DELETE",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4390),
                            Description = "Delete User",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4390),
                            Name = "Delete User",
                            ParentId = 4,
                            Type = 3,
                            Url = "Admin/User/Delete",
                            ViewOrder = 3
                        },
                        new
                        {
                            ModuleId = 17,
                            Area = "Admin",
                            Code = "ACTION_ROLE_ADD",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4394),
                            Description = "Add Role",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4394),
                            Name = "Add Role",
                            ParentId = 5,
                            Type = 3,
                            Url = "Admin/Role/Add",
                            ViewOrder = 1
                        },
                        new
                        {
                            ModuleId = 18,
                            Area = "Admin",
                            Code = "ACTION_ROLE_EDIT",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4394),
                            Description = "Edit Role",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4398),
                            Name = "Edit Role",
                            ParentId = 5,
                            Type = 3,
                            Url = "Admin/Role/Edit",
                            ViewOrder = 2
                        },
                        new
                        {
                            ModuleId = 19,
                            Area = "Admin",
                            Code = "ACTION_ROLE_DELETE",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4398),
                            Description = "Delete Role",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4398),
                            Name = "Delete Role",
                            ParentId = 5,
                            Type = 3,
                            Url = "Admin/Role/Delete",
                            ViewOrder = 3
                        },
                        new
                        {
                            ModuleId = 20,
                            Area = "Admin",
                            Code = "ACTION_PERMISSION_ADD",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4406),
                            Description = "Add Permission",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4406),
                            Name = "Add Permission",
                            ParentId = 6,
                            Type = 3,
                            Url = "Admin/Permission/Add",
                            ViewOrder = 1
                        },
                        new
                        {
                            ModuleId = 21,
                            Area = "Admin",
                            Code = "ACTION_PERMISSION_EDIT",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4406),
                            Description = "Edit Permission",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4406),
                            Name = "Edit Permission",
                            ParentId = 6,
                            Type = 3,
                            Url = "Admin/Permission/Edit",
                            ViewOrder = 2
                        },
                        new
                        {
                            ModuleId = 22,
                            Area = "Admin",
                            Code = "ACTION_PERMISSION_DELETE",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4410),
                            Description = "Delete Permission",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4410),
                            Name = "Delete Permission",
                            ParentId = 6,
                            Type = 3,
                            Url = "Admin/Permission/Delete",
                            ViewOrder = 3
                        },
                        new
                        {
                            ModuleId = 23,
                            Area = "Admin",
                            Code = "ACTION_MODULE_ADD",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4413),
                            Description = "Add Module",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4413),
                            Name = "Add Module",
                            ParentId = 8,
                            Type = 3,
                            Url = "Admin/Module/Add",
                            ViewOrder = 1
                        },
                        new
                        {
                            ModuleId = 24,
                            Area = "Admin",
                            Code = "ACTION_MODULE_EDIT",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4477),
                            Description = "Edit Module",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4477),
                            Name = "Edit Module",
                            ParentId = 8,
                            Type = 3,
                            Url = "Admin/Module/Edit",
                            ViewOrder = 2
                        },
                        new
                        {
                            ModuleId = 25,
                            Area = "Admin",
                            Code = "ACTION_MODULE_DELETE",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4481),
                            Description = "Delete Module",
                            IsClickable = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 206, DateTimeKind.Local).AddTicks(4481),
                            Name = "Delete Module",
                            ParentId = 8,
                            Type = 3,
                            Url = "Admin/Module/Delete",
                            ViewOrder = 3
                        });
                });

            modelBuilder.Entity("Leadzum.Framework.Data.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsConfigurable");

                    b.Property<int>("ModuleId");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(50);

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Priority");

                    b.HasKey("PermissionId");

                    b.HasIndex("ModuleId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Leadzum.Framework.Data.Entities.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AllowAccess");

                    b.Property<int?>("CreatedByUserId");

                    b.Property<DateTime>("CreatedOnDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int?>("LastModifiedByUserId");

                    b.Property<DateTime>("LastModifiedOnDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int>("PermissionId");

                    b.Property<int?>("RoleId")
                        .IsRequired();

                    b.Property<int?>("UserId")
                        .IsRequired();

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Leadzum.Framework.Data.Entities.SystemConfig", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConfigCategory")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ConfigValue");

                    b.Property<int>("DataType");

                    b.Property<string>("DefaultValue");

                    b.Property<bool>("IsVisible");

                    b.Property<int?>("LastModifiedByUserId");

                    b.Property<DateTime>("LastModifiedOnDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int>("Length");

                    b.Property<string>("ValidationExpression")
                        .HasMaxLength(1000);

                    b.Property<int>("ViewOrder");

                    b.HasKey("ConfigId");

                    b.HasIndex("ConfigName")
                        .IsUnique();

                    b.ToTable("SystemConfigs");

                    b.HasData(
                        new
                        {
                            ConfigId = 1,
                            ConfigCategory = "SYS_GENERAL",
                            ConfigName = "DateFormat",
                            ConfigValue = "dd-MMM-yyyy",
                            DataType = 2,
                            DefaultValue = "dd-MMM-yyyy",
                            IsVisible = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 187, DateTimeKind.Local).AddTicks(7375),
                            Length = 15,
                            ViewOrder = 0
                        },
                        new
                        {
                            ConfigId = 2,
                            ConfigCategory = "SYS_GENERAL",
                            ConfigName = "ShortTimeFormat",
                            ConfigValue = "HH:mm",
                            DataType = 2,
                            DefaultValue = "HH:mm",
                            IsVisible = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 188, DateTimeKind.Local).AddTicks(4032),
                            Length = 15,
                            ViewOrder = 0
                        },
                        new
                        {
                            ConfigId = 3,
                            ConfigCategory = "SYS_GENERAL",
                            ConfigName = "LongTimeFormat",
                            ConfigValue = "HH:mm:ss",
                            DataType = 2,
                            DefaultValue = "HH:mm:ss",
                            IsVisible = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 188, DateTimeKind.Local).AddTicks(4084),
                            Length = 15,
                            ViewOrder = 0
                        },
                        new
                        {
                            ConfigId = 4,
                            ConfigCategory = "SYS_SMTP",
                            ConfigName = "Server",
                            ConfigValue = "",
                            DataType = 2,
                            DefaultValue = "",
                            IsVisible = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 188, DateTimeKind.Local).AddTicks(4087),
                            Length = 30,
                            ViewOrder = 0
                        },
                        new
                        {
                            ConfigId = 5,
                            ConfigCategory = "SYS_SMTP",
                            ConfigName = "Port",
                            ConfigValue = "25",
                            DataType = 1,
                            DefaultValue = "25",
                            IsVisible = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 188, DateTimeKind.Local).AddTicks(4091),
                            Length = 0,
                            ViewOrder = 0
                        },
                        new
                        {
                            ConfigId = 6,
                            ConfigCategory = "SYS_SMTP",
                            ConfigName = "RequireAuthentication",
                            ConfigValue = "False",
                            DataType = 3,
                            DefaultValue = "False",
                            IsVisible = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 188, DateTimeKind.Local).AddTicks(4099),
                            Length = 0,
                            ViewOrder = 0
                        },
                        new
                        {
                            ConfigId = 7,
                            ConfigCategory = "SYS_SMTP",
                            ConfigName = "UserName",
                            ConfigValue = "",
                            DataType = 2,
                            DefaultValue = "",
                            IsVisible = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 188, DateTimeKind.Local).AddTicks(4099),
                            Length = 30,
                            ViewOrder = 0
                        },
                        new
                        {
                            ConfigId = 8,
                            ConfigCategory = "SYS_SMTP",
                            ConfigName = "Password",
                            ConfigValue = "",
                            DataType = 2,
                            DefaultValue = "",
                            IsVisible = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 188, DateTimeKind.Local).AddTicks(4103),
                            Length = 30,
                            ViewOrder = 0
                        },
                        new
                        {
                            ConfigId = 9,
                            ConfigCategory = "SYS_SMTP",
                            ConfigName = "EnableSSL",
                            ConfigValue = "False",
                            DataType = 2,
                            DefaultValue = "False",
                            IsVisible = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 188, DateTimeKind.Local).AddTicks(4107),
                            Length = 0,
                            ViewOrder = 0
                        },
                        new
                        {
                            ConfigId = 10,
                            ConfigCategory = "SYS_SMTP",
                            ConfigName = "MailFrom",
                            ConfigValue = "",
                            DataType = 2,
                            DefaultValue = "",
                            IsVisible = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 188, DateTimeKind.Local).AddTicks(4111),
                            Length = 30,
                            ViewOrder = 0
                        },
                        new
                        {
                            ConfigId = 11,
                            ConfigCategory = "SYS_SMTP",
                            ConfigName = "DisplayName",
                            ConfigValue = "",
                            DataType = 2,
                            DefaultValue = "",
                            IsVisible = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 188, DateTimeKind.Local).AddTicks(4111),
                            Length = 30,
                            ViewOrder = 0
                        },
                        new
                        {
                            ConfigId = 12,
                            ConfigCategory = "SYS_SMTP",
                            ConfigName = "Activated",
                            ConfigValue = "False",
                            DataType = 3,
                            DefaultValue = "False",
                            IsVisible = true,
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 188, DateTimeKind.Local).AddTicks(4115),
                            Length = 0,
                            ViewOrder = 0
                        });
                });

            modelBuilder.Entity("Leadzum.Framework.Data.IdentityEntities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<int?>("CreatedByUserId");

                    b.Property<DateTime>("CreatedOnDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("IsAuthorized");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("LastModifiedByUserId");

                    b.Property<DateTime>("LastModifiedOnDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<int>("PasswordChangeStatus");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<int>("UserTypeId");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0bc136a0-b29e-46a9-81e0-8a56ed9fad19",
                            CreatedOnDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Super Admin",
                            Email = "superadmin@mail.com",
                            EmailConfirmed = false,
                            IsAuthorized = false,
                            IsDeleted = false,
                            LastModifiedOnDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@MAIL.COM",
                            NormalizedUserName = "SUPERADMIN@MAIL.COM",
                            PasswordChangeStatus = 0,
                            PasswordHash = "AQAAAAEAACcQAAAAEKxbYuOfS48Bfwu+BYKdxRym5FemYaYoUoAhdWYL9RHOh7e0srPu2FRaDZlOSra4Mw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@mail.com",
                            UserTypeId = 0
                        });
                });

            modelBuilder.Entity("Leadzum.Framework.Data.IdentityEntities.IdentityRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<int?>("CreatedByUserId");

                    b.Property<DateTime>("CreatedOnDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Description")
                        .HasMaxLength(256);

                    b.Property<int?>("LastModifiedByUserId");

                    b.Property<DateTime>("LastModifiedOnDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("UserCategory");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "57a38a87-5932-4f99-9e73-7c927de6f769",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 174, DateTimeKind.Local).AddTicks(8581),
                            Description = "Web Service Client",
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 175, DateTimeKind.Local).AddTicks(6819),
                            Name = "Web Service Client",
                            RoleCode = "SERVICE_CLIENT",
                            UserCategory = 1
                        },
                        new
                        {
                            Id = 100,
                            ConcurrencyStamp = "5eeb0b3c-0594-409b-a13d-71a480761d20",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 178, DateTimeKind.Local).AddTicks(2391),
                            Description = "Super Admin",
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 178, DateTimeKind.Local).AddTicks(2403),
                            Name = "Super Admin",
                            RoleCode = "SUPER_ADMIN",
                            UserCategory = 2
                        },
                        new
                        {
                            Id = 101,
                            ConcurrencyStamp = "18bc1e77-2d32-41d9-9f6a-03bb2067f525",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 178, DateTimeKind.Local).AddTicks(2802),
                            Description = "Admin",
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 178, DateTimeKind.Local).AddTicks(2802),
                            Name = "Admin",
                            RoleCode = "ADMIN",
                            UserCategory = 2
                        },
                        new
                        {
                            Id = 200,
                            ConcurrencyStamp = "34b2a1fe-10d3-4916-b785-05f6a36b8460",
                            CreatedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 178, DateTimeKind.Local).AddTicks(3161),
                            Description = "Member",
                            LastModifiedOnDate = new DateTime(2019, 9, 28, 23, 7, 15, 178, DateTimeKind.Local).AddTicks(3161),
                            Name = "Member",
                            RoleCode = "MEMBER",
                            UserCategory = 3
                        });
                });

            modelBuilder.Entity("Leadzum.Framework.Data.IdentityEntities.IdentityRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Leadzum.Framework.Data.IdentityEntities.IdentityUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Leadzum.Framework.Data.IdentityEntities.IdentityUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Leadzum.Framework.Data.IdentityEntities.IdentityUserRole", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 100
                        });
                });

            modelBuilder.Entity("Leadzum.Framework.Data.IdentityEntities.IdentityUserToken", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Leadzum.Framework.Data.Entities.EventLog", b =>
                {
                    b.HasOne("Leadzum.Framework.Data.Entities.EventLogType", "EventLogType")
                        .WithMany("EventLogs")
                        .HasForeignKey("LogTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Leadzum.Framework.Data.Entities.List", b =>
                {
                    b.HasOne("Leadzum.Framework.Data.Entities.List", "Parent")
                        .WithMany("Lists")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Leadzum.Framework.Data.Entities.Module", b =>
                {
                    b.HasOne("Leadzum.Framework.Data.Entities.Module", "Parent")
                        .WithMany("Modules")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Leadzum.Framework.Data.Entities.Permission", b =>
                {
                    b.HasOne("Leadzum.Framework.Data.Entities.Module", "Module")
                        .WithMany("Permissions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Leadzum.Framework.Data.Entities.RolePermission", b =>
                {
                    b.HasOne("Leadzum.Framework.Data.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Leadzum.Framework.Data.IdentityEntities.IdentityRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Leadzum.Framework.Data.IdentityEntities.ApplicationUser", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Leadzum.Framework.Data.IdentityEntities.IdentityRoleClaim", b =>
                {
                    b.HasOne("Leadzum.Framework.Data.IdentityEntities.IdentityRole", "Role")
                        .WithMany("Claims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Leadzum.Framework.Data.IdentityEntities.IdentityUserClaim", b =>
                {
                    b.HasOne("Leadzum.Framework.Data.IdentityEntities.ApplicationUser", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Leadzum.Framework.Data.IdentityEntities.IdentityUserLogin", b =>
                {
                    b.HasOne("Leadzum.Framework.Data.IdentityEntities.ApplicationUser", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Leadzum.Framework.Data.IdentityEntities.IdentityUserRole", b =>
                {
                    b.HasOne("Leadzum.Framework.Data.IdentityEntities.IdentityRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Leadzum.Framework.Data.IdentityEntities.ApplicationUser", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Leadzum.Framework.Data.IdentityEntities.IdentityUserToken", b =>
                {
                    b.HasOne("Leadzum.Framework.Data.IdentityEntities.ApplicationUser", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
